version: '3'

services:
  cockpit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3001}:80"  # Nastavení Coolify portu
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - COOLIFY_URL=${COOLIFY_URL}
      - COOLIFY_BRANCH=${COOLIFY_BRANCH}
      - COOLIFY_CONTAINER_NAME=${COOLIFY_CONTAINER_NAME}
    restart: unless-stopped
